namespace: toy-production
global:
imageTag: "<GIT_SHA_OR_TAG>"
awsRegion: "us-east-1"
healthDeepCheck: "true"
images:
userServiceRepo: "<terraform_output_ecr_user_repo>"
productServiceRepo: "<terraform_output_ecr_product_repo>"
orderServiceRepo: "<terraform_output_ecr_order_repo>"
redis:
url: "redis://<terraform_output_redis_endpoint>:6379"
databaseSecret:
awsSecretName: "<terraform_output_db_secret_name>"
property: "database_url"